using FluentAssertions;
using Mycelium.Backend.Services.Singletons;
using Mycelium.Plex.Services.Smart;
using Xunit;

namespace Mycelium.Tests;

/// <summary>
/// The blurb a generated playlist carries in Plex. Shape rather than wording: the wording belongs to
/// the catalog, and pinning it here would mean editing two files to reword one line.
/// </summary>
public class PlaylistSummaryTests
{
    private static readonly PlexSmartFilter AnyFilter = new(
        PlexSmartFilter.ArtistType, new PlexCondition("track.userRating", PlexOp.GreaterThan, "7"));

    private static StockPlaylistDefinition Definition(string? description, params string[] details) =>
        new("id", "Title", description, details, AnyFilter);

    /// <summary>
    /// Tagline, then the rules one clause per line, then who it was built for — blank-line separated,
    /// because Plex renders a summary as plain text and whitespace is the only structure available.
    /// </summary>
    [Fact]
    public void A_full_summary_reads_tagline_then_rules_then_credit()
    {
        var summary = PlaylistSummary.For(
            Definition("What it's for", "First rule", "Second rule"), "noggog");

        summary.Should().Be(
            "What it's for\n\n• First rule\n• Second rule\n\nGenerated by Mycelium for noggog.");
    }

    /// <summary>
    /// A tier row has no tagline — its title already says "4★+" — and must not open with a blank line
    /// where one would have been.
    /// </summary>
    [Fact]
    public void A_row_with_no_tagline_opens_on_its_rules()
    {
        var summary = PlaylistSummary.For(Definition(null, "Rated 4★ and up"), "noggog");

        summary.Should().Be("• Rated 4★ and up\n\nGenerated by Mycelium for noggog.");
    }

    /// <summary>
    /// The clauses are carried through from the definition, so a rule that only some users have is only
    /// described for those users — the summary can't claim a rule the filter doesn't hold.
    /// </summary>
    [Fact]
    public void Only_the_clauses_the_definition_carries_are_described()
    {
        var summary = PlaylistSummary.For(Definition("Tagline", "The one rule"), "noggog");

        summary.Should().Contain("• The one rule");
        summary.Should().NotContain("• \n");
        summary.Split('•').Should().HaveCount(2);
    }

    /// <summary>
    /// With no name to credit the line still names the app: "who built this" is the half a reader can't
    /// work out for themselves, and dropping the whole line would lose it.
    /// </summary>
    [Theory]
    [InlineData(null)]
    [InlineData("")]
    [InlineData("   ")]
    public void An_unnamed_user_still_leaves_the_app_credited(string? username)
    {
        var summary = PlaylistSummary.For(Definition("Tagline", "A rule"), username);

        summary.Should().EndWith("Generated by Mycelium.");
    }
}
