namespace Mycelium.Backend.Services.Singletons;

/// <summary>
/// The blurb a generated playlist carries in Plex — what it is for, what it actually selects, and who
/// it was built for.
///
/// <para><b>Why it is worth writing.</b> A smart playlist in a Plex sidebar is a name and a rule query:
/// the name is short by necessity and the rules are only legible in the filter editor, so months later
/// nobody can say why "Frontier" holds what it holds. The summary is the one field Plex shows next to
/// the playlist everywhere, and it costs one request to fill in.</para>
///
/// <para><b>Composed from the definition, never written by hand.</b> Both halves — the tagline and the
/// clauses — are the same strings the Playlists page shows, generated by
/// <see cref="SmartPlaylistCatalog"/> from the same options the filter is. So a rule that only exists
/// for some users is only described for those users, and there is no second copy of the wording to
/// drift out of step with the rules it describes.</para>
///
/// <para><b>The credit at the end is the point of the last line.</b> These playlists are per-account —
/// the same title means different tracks in two people's sidebars, because ratings and play counts are
/// their own — so a summary that didn't name whose taste it was built from would be describing a
/// playlist that doesn't exist.</para>
/// </summary>
public static class PlaylistSummary
{
    /// <summary>What every generated playlist is signed with, whoever it belongs to.</summary>
    public const string Signature = "Generated by Mycelium";

    /// <summary>
    /// The summary for one definition, as built for <paramref name="username"/>.
    ///
    /// <para>Three paragraphs, any of which may be absent: the tagline (a tier row has none — its title
    /// already says "4★+" and a tagline there would only repeat it), the rules one clause per line, and
    /// the credit. Blank-line separated because Plex renders the summary as plain text, so the only
    /// structure available is the whitespace.</para>
    /// </summary>
    /// <param name="username">
    /// Who the playlist is for. Null or blank when the caller has no name to give — an account with no
    /// <c>preferred_username</c> claim — in which case the credit still names the app, since "who built
    /// this" is the half of that line a reader can't work out for themselves.
    /// </param>
    public static string For(StockPlaylistDefinition definition, string? username)
    {
        var paragraphs = new List<string>();

        if (!string.IsNullOrWhiteSpace(definition.Description))
        {
            paragraphs.Add(definition.Description.Trim());
        }

        if (definition.Details.Count > 0)
        {
            paragraphs.Add(string.Join("\n", definition.Details.Select(detail => $"• {detail}")));
        }

        paragraphs.Add(Credit(username));

        return string.Join("\n\n", paragraphs);
    }

    /// <summary>The closing line: the app, and the user the rules were generated for.</summary>
    private static string Credit(string? username) =>
        string.IsNullOrWhiteSpace(username)
            ? $"{Signature}."
            : $"{Signature} for {username.Trim()}.";
}
